config/routes.rb
Rails.application.routes.draw do
  root to: 'registries#index'
  post 'reports/estadistica'
  get 'reports/estadistica1'
  get 'reports/reporte'
  get 'reports/:id/validacion', to: 'reports#validacion', as: 'reports_validacion'
  get 'reports/:id/verificacion', to: 'reports#verificacion', as: 'reports_verificacion'
  get 'reports/:id/caractula1', to: 'reports#caractula1', as: 'reports_caractula1'
  get 'reports/:id/caractula2', to: 'reports#caractula2', as: 'reports_caractula2'

  get 'expedients/mostrar_expedientes', to: 'expedients#mostrar_expedientes', as: 'mostrar_expedientes'
  get 'cities/mostrar_ciudades', to: 'cities#mostrar_ciudades', as: 'mostrar_ciudades'
  get 'authorities/mostrar_autoridades', to: 'authorities#mostrar_autoridades', as: 'mostrar_autoridades'

  get 'reports/verificacion'
  # get 'reports/validacion/:id'
  get 'reports/bitacora'
  post 'reports/bitacora1'
  # get 'reports/caractula1'

  # get 'reports/caractula2'

  # resources :reports
  resources :validations
  resources :verifications
  resources :specialties
  resources :registries
  resources :titles
  resources :authorities
  resources :results
  resources :experts
  resources :cities
  resources :expedients

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/verification.rb
class Verification < ApplicationRecord
  belongs_to :city
  belongs_to :registry
  belongs_to :expedient
  belongs_to :expert
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  before_action :set_verification, only: [:show, :edit, :update, :destroy]

  # GET /verifications
  # GET /verifications.json
  def index
    @verifications = Verification.all
  end

  # GET /verifications/1
  # GET /verifications/1.json
  def show
  end

  # GET /verifications/new
  def new
    @verification = Verification.new
  end

  # GET /verifications/1/edit
  def edit
  end

  # POST /verifications
  # POST /verifications.json
  def create
    @verification = Verification.new(verification_params)

    respond_to do |format|
      if @verification.save
        format.html { redirect_to @verification, notice: 'Verification was successfully created.' }
        format.json { render :show, status: :created, location: @verification }
      else
        format.html { render :new }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verifications/1
  # PATCH/PUT /verifications/1.json
  def update
    respond_to do |format|
      if @verification.update(verification_params)
        format.html { redirect_to @verification, notice: 'Verification was successfully updated.' }
        format.json { render :show, status: :ok, location: @verification }
      else
        format.html { render :edit }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verifications/1
  # DELETE /verifications/1.json
  def destroy
    @verification.destroy
    respond_to do |format|
      format.html { redirect_to verifications_url, notice: 'Verification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verification
      @verification = Verification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verification_params
      params.require(:verification).permit(:city_id, :fecha, :registry_id, :expedient_id, :incluye_expediente, :coincide_expediente, :incluye_anexos, :coinciden_anexos, :anexos_equipos_de_computo, :anexos_equipo_de_comunicacion, :anexos_material_fotografico, :anexos_disp_alm_elect, :anexos_componentes_electronicos, :otros, :expert_id)
    end
end

app/helpers/verifications_helper.rb
module VerificationsHelper
end

app/views/verifications/_form.html.slim
= simple_form_for verification do |f|
  = f.input :city_id do
    = f.select :city_id,  City.all.map { |c| ["#{c.ciudad}, #{c.estado}", c.id] }
  = f.input :fecha, as: :date
  = f.input :registry_id do
    = f.select :registry_id, Registry.joins(:result).where("resultado is not 'NOTIFICACION'").map { |r| ["FOLIO: #{r.folio.to_s}/#{r.year_folio.to_s} --> #{r.expedient.expediente}", r.id] }
  = f.input :expedient_id do
    = f.select :expedient_id,  Expedient.all.map { |e| [e.expediente, e.id] }
  = f.input :incluye_expediente, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
          label: "La solicitud Ministerial, Judicial u otra. Incluye Expediente original y/o copia."
  = f.input :coincide_expediente, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
          label: "El número de expediente original y/o copia coincide con el número de la solicitud original."
  = f.input :incluye_anexos, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
          label: "La solicitud Ministerial, Judicial u otra. Incluye Anexos."
  = f.input :coinciden_anexos, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
        label: "Los anexos coinciden con lo descrito en la solicitud origina."
  = f.input :anexos_equipos_de_computo, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
        label: "Los anexos se componen de equipo de cómputo (CPU, Monitores, Scanners, videojuegos, etc.)."
  = f.input :anexos_equipo_de_comunicacion, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
        label: "Los anexos se componen de equipo de comunicación (teléfonos, radio comunicadores, agendas electrónicas, antenas)."
  = f.input :anexos_material_fotografico, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
        label: "Los anexos se componen de material fotográfico."
  = f.input :anexos_disp_alm_elect, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
        label: "Los anexos se componen de dispositivos de almacenamiento electrónico o magnético (3½, CDs, cartuchos de cinta magnética, memoria electrónica, etc.)."
  = f.input :anexos_componentes_electronicos, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, \
        label: "Los anexos se componen de dispositivos electrónicos."
  = f.input :otros, collection: [["SI", 0],["NO", 1],["NO APLICA", 2]], include_blank: false, label: "Otros."
  = f.input :expert_id do
    = f.select :expert_id,  Expert.all.map { |e| [e.nombre, e.id] }
  br
  = f.submit

app/views/verifications/edit.html.erb
<h1>Editing Verification</h1>

<%= render 'form', verification: @verification %>

<%= link_to 'Show', @verification %> |
<%= link_to 'Back', verifications_path %>

app/views/verifications/index.html.slim
p#notice= notice
- r = ["SI","NO","NO APLICA"]
h1 Verifications
table
  thead
    tr
      th City
      th Fecha
      th Registry
      th Expedient
      th Incluye expediente
      th Coincide expediente
      th Incluye anexos
      th Coinciden anexos
      th Anexos equipos de computo
      th Anexos equipo de comunicacion
      th Anexos material fotografico
      th Anexos disp alm elect
      th Anexos componentes electronicos
      th Otros
      th Verificador
      th colspan="4"
  tbody
    - @verifications.each do |verification|
      tr
        td= "#{verification.city.ciudad}, #{verification.city.estado}"
        td= verification.fecha
        td= verification.registry.folio
        td= verification.expedient.expediente
        td= r[verification.incluye_expediente]
        td= r[verification.coincide_expediente]
        td= r[verification.incluye_anexos]
        td= r[verification.coinciden_anexos]
        td= r[verification.anexos_equipos_de_computo]
        td= r[verification.anexos_equipo_de_comunicacion]
        td= r[verification.anexos_material_fotografico]
        td= r[verification.anexos_disp_alm_elect]
        td= r[verification.anexos_componentes_electronicos]
        td= r[verification.otros]
        td= verification.expert.nombre
        td= link_to 'Show', verification
        td= link_to 'Edit', edit_verification_path(verification)
        td= link_to 'Formato', reports_verificacion_path(verification)
        td= link_to 'Destroy', verification, method: :delete, data: { confirm: 'Are you sure?'}
br
= link_to 'New Verification', new_verification_path

app/views/verifications/new.html.erb
<h1>New Verification</h1>

<%= render 'form', verification: @verification %>

<%= link_to 'Back', verifications_path %>

app/views/verifications/show.html.slim
p#notice= notice
- r = ["SI","NO","NO APLICA"]
p
  strong City:
  = "#{@verification.city.ciudad}, #{@verification.city.estado}"
p
  strong Fecha:
  = @verification.fecha
p
  strong Registry:
  = @verification.registry.folio
p
  strong Expedient:
  = @verification.expedient.expediente
p
  strong Incluye expediente:
  = r[@verification.incluye_expediente]
p
  strong Coincide expediente:
  = r[@verification.coincide_expediente]
p
  strong Incluye anexos:
  = r[@verification.incluye_anexos]
p
  strong Coinciden anexos:
  = r[@verification.coinciden_anexos]
p
  strong Anexos equipos de computo:
  = r[@verification.anexos_equipos_de_computo]
p
  strong Anexos equipo de comunicacion:
  = r[@verification.anexos_equipo_de_comunicacion]
p
  strong Anexos material fotografico:
  = r[@verification.anexos_material_fotografico]
p
  strong Anexos disp alm elect:
  = r[@verification.anexos_disp_alm_elect]
p
  strong Anexos componentes electronicos:
  = r[@verification.anexos_componentes_electronicos]
p
  strong Otros:
  = r[@verification.otros]
p
  strong Verificador:
  = @verification.expert.nombre
= link_to 'Edit', edit_verification_path(@verification)
| |
= link_to 'Back', verifications_path