config/routes.rb
Rails.application.routes.draw do
  root to: 'registries#index'
  post 'reports/estadistica'
  get 'reports/estadistica1'
  get 'reports/reporte'
  get 'reports/:id/validacion', to: 'reports#validacion', as: 'reports_validacion'
  get 'reports/:id/verificacion', to: 'reports#verificacion', as: 'reports_verificacion'
  get 'reports/:id/caractula1', to: 'reports#caractula1', as: 'reports_caractula1'
  get 'reports/:id/caractula2', to: 'reports#caractula2', as: 'reports_caractula2'

  get 'expedients/mostrar_expedientes', to: 'expedients#mostrar_expedientes', as: 'mostrar_expedientes'
  get 'cities/mostrar_ciudades', to: 'cities#mostrar_ciudades', as: 'mostrar_ciudades'
  get 'authorities/mostrar_autoridades', to: 'authorities#mostrar_autoridades', as: 'mostrar_autoridades'

  get 'reports/verificacion'
  # get 'reports/validacion/:id'
  get 'reports/bitacora'
  post 'reports/bitacora1'
  # get 'reports/caractula1'

  # get 'reports/caractula2'

  # resources :reports
  resources :validations
  resources :verifications
  resources :specialties
  resources :registries
  resources :titles
  resources :authorities
  resources :results
  resources :experts
  resources :cities
  resources :expedients

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/result.rb
class Result < ApplicationRecord
  has_many :registries
  validates :resultado, uniqueness: true
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:resultado)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :resultado %>
    <%= form.text_field :resultado, id: :result_resultado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th>Resultado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.resultado %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resultado:</strong>
  <%= @result.resultado %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>