config/routes.rb
Rails.application.routes.draw do
  root to: 'registries#index'
  post 'reports/estadistica'
  get 'reports/estadistica1'
  get 'reports/reporte'
  get 'reports/:id/validacion', to: 'reports#validacion', as: 'reports_validacion'
  get 'reports/:id/verificacion', to: 'reports#verificacion', as: 'reports_verificacion'
  get 'reports/:id/caractula1', to: 'reports#caractula1', as: 'reports_caractula1'
  get 'reports/:id/caractula2', to: 'reports#caractula2', as: 'reports_caractula2'

  get 'expedients/mostrar_expedientes', to: 'expedients#mostrar_expedientes', as: 'mostrar_expedientes'
  get 'cities/mostrar_ciudades', to: 'cities#mostrar_ciudades', as: 'mostrar_ciudades'
  get 'authorities/mostrar_autoridades', to: 'authorities#mostrar_autoridades', as: 'mostrar_autoridades'

  get 'reports/verificacion'
  # get 'reports/validacion/:id'
  get 'reports/bitacora'
  post 'reports/bitacora1'
  # get 'reports/caractula1'

  # get 'reports/caractula2'

  # resources :reports
  resources :validations
  resources :verifications
  resources :specialties
  resources :registries
  resources :titles
  resources :authorities
  resources :results
  resources :experts
  resources :cities
  resources :expedients

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/authority.rb
class Authority < ApplicationRecord
  has_many :registries
  validates :nombre, presence: true
  validates :puesto, presence: true
end

app/controllers/authorities_controller.rb
class AuthoritiesController < ApplicationController
  before_action :set_authority, only: [:show, :edit, :update, :destroy]

  # GET /authorities
  # GET /authorities.json
  def index
    @authorities = Authority.all
  end

  # GET /authorities/1
  # GET /authorities/1.json
  def show
  end

  # GET /authorities/new
  def new
    @authority = Authority.new
  end

  def mostrar_autoridades
    @autoridades = Authority.order(:nombre).where("nombre like :search", search: "%#{params[:term]}%")
    render json: @autoridades.map{|a| a.nombre}
  end

  # GET /authorities/1/edit
  def edit
  end

  # POST /authorities
  # POST /authorities.json
  def create
    @authority = Authority.new(authority_params)

    respond_to do |format|
      if @authority.save
        format.html { redirect_to @authority, notice: 'Authority was successfully created.' }
        format.json { render :show, status: :created, location: @authority }
      else
        format.html { render :new }
        format.json { render json: @authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorities/1
  # PATCH/PUT /authorities/1.json
  def update
    respond_to do |format|
      if @authority.update(authority_params)
        format.html { redirect_to @authority, notice: 'Authority was successfully updated.' }
        format.json { render :show, status: :ok, location: @authority }
      else
        format.html { render :edit }
        format.json { render json: @authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorities/1
  # DELETE /authorities/1.json
  def destroy
    @authority.destroy
    respond_to do |format|
      format.html { redirect_to authorities_url, notice: 'Authority was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authority
      @authority = Authority.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authority_params
      params.require(:authority).permit(:nombre, :puesto)
    end
end

app/helpers/authorities_helper.rb
module AuthoritiesHelper
end

app/views/authorities/_form.html.slim
= simple_form_for authority do |f|
  = f.error_notification
  = f.input :nombre
  = f.select :puesto, ["MPF","PFM","JDOS","POL. FED.","PGJ EDO.","OTROS"]
  br
  = f.submit

app/views/authorities/edit.html.erb
<h1>Editing Authority</h1>

<%= render 'form', authority: @authority %>

<%= link_to 'Show', @authority %> |
<%= link_to 'Back', authorities_path %>

app/views/authorities/index.html.slim
p#notice= notice
h1 Authorities
table
  thead
    tr
      th Nombre
      th Puesto
      th colspan="3"
  tbody
    - @authorities.each do |authority|
      tr
        td= authority.nombre
        td= authority.puesto
        td= link_to 'Show', authority
        td= link_to 'Edit', edit_authority_path(authority)
        td= link_to 'Destroy', authority, method: :delete, data: {confirm: 'Are you sure?'}
br/
= link_to 'New Authority', new_authority_path

app/views/authorities/new.html.erb
<h1>New Authority</h1>

<%= render 'form', authority: @authority %>

<%= link_to 'Back', authorities_path %>

app/views/authorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @authority.nombre %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @authority.puesto %>
</p>



<%= link_to 'Edit', edit_authority_path(@authority) %> |
<%= link_to 'Back', authorities_path %>