config/routes.rb
Rails.application.routes.draw do
  root to: 'registries#index'
  post 'reports/estadistica'
  get 'reports/estadistica1'
  get 'reports/reporte'
  get 'reports/:id/validacion', to: 'reports#validacion', as: 'reports_validacion'
  get 'reports/:id/verificacion', to: 'reports#verificacion', as: 'reports_verificacion'
  get 'reports/:id/caractula1', to: 'reports#caractula1', as: 'reports_caractula1'
  get 'reports/:id/caractula2', to: 'reports#caractula2', as: 'reports_caractula2'

  get 'expedients/mostrar_expedientes', to: 'expedients#mostrar_expedientes', as: 'mostrar_expedientes'
  get 'cities/mostrar_ciudades', to: 'cities#mostrar_ciudades', as: 'mostrar_ciudades'
  get 'authorities/mostrar_autoridades', to: 'authorities#mostrar_autoridades', as: 'mostrar_autoridades'

  get 'reports/verificacion'
  # get 'reports/validacion/:id'
  get 'reports/bitacora'
  post 'reports/bitacora1'
  # get 'reports/caractula1'

  # get 'reports/caractula2'

  # resources :reports
  resources :validations
  resources :verifications
  resources :specialties
  resources :registries
  resources :titles
  resources :authorities
  resources :results
  resources :experts
  resources :cities
  resources :expedients

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/validation.rb
class Validation < ApplicationRecord
  belongs_to :registry
  belongs_to :expert
  belongs_to :city

  accepts_nested_attributes_for :registry
  accepts_nested_attributes_for :expert
  accepts_nested_attributes_for :city

  validates_uniqueness_of :registry_id, scope: :expert_id

  validates :expert, presence: true
  validates :registry, presence: true
  validates :registry, uniqueness: true

end

app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
  before_action :set_validation, only: [:show, :edit, :update, :destroy]

  # GET /validations
  # GET /validations.json
  def index
    @validations = Validation.all
  end

  # GET /validations/1
  # GET /validations/1.json
  def show
  end

  # GET /validations/new
  def new
    @validation = Validation.new
  end

  # GET /validations/1/edit
  def edit
  end

  # POST /validations
  # POST /validations.json
  def create
    @validation = Validation.new(validation_params)

    respond_to do |format|
      if @validation.save
        format.html { redirect_to @validation, notice: 'Validation was successfully created.' }
        format.json { render :show, status: :created, location: @validation }
      else
        format.html { render :new }
        format.json { render json: @validation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /validations/1
  # PATCH/PUT /validations/1.json
  def update
    respond_to do |format|
      if @validation.update(validation_params)
        format.html { redirect_to @validation, notice: 'Validation was successfully updated.' }
        format.json { render :show, status: :ok, location: @validation }
      else
        format.html { render :edit }
        format.json { render json: @validation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /validations/1
  # DELETE /validations/1.json
  def destroy
    @validation.destroy
    respond_to do |format|
      format.html { redirect_to validations_url, notice: 'Validation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_validation
      @validation = Validation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def validation_params
      params.require(:validation).permit(:registry_id, :expert_id, city_attributes: City.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/helpers/validations_helper.rb
module ValidationsHelper
end

app/views/validations/_form.html.slim
= simple_form_for validation do |f|
  = f.input :registry_id, error: "SOLO DEBE HABER UNA VALIDADCION POR EXPEDIENTE" do
    = f.select :registry_id, Registry.joins(:result).where("resultado is not ?", "NOTIFICACION").order(:year_folio,:folio).map { |r| ["FOLIO: #{r.folio.to_s}/#{r.year_folio.to_s} --> #{r.expedient.expediente}", r.id] }
  = f.input :expert_id, error: "SOLO DEBE HABER UNA VALIDADCION POR EXPEDIENTE" do
    = f.select :expert_id, Expert.all.map {|e| [e.nombre, e.id]}
  = f.association :city do |c|
    = c.input :ciudad
    = c.input :estado
  = f.submit

app/views/validations/edit.html.erb
<h1>Editing Validation</h1>

<%= render 'form', validation: @validation %>

<%= link_to 'Show', @validation %> |
<%= link_to 'Back', validations_path %>

app/views/validations/index.html.slim
p#notice= notice
h1 Validations
table
  thead
    tr
      th Registry
      th Validador
      th Ciudad
      th Estado
      th colspan="4"
  tbody
    - @validations.each do |validation|
      tr
        td= "Folio :#{validation.registry.folio.to_s}/#{validation.registry.year_folio.to_s} --> #{validation.registry.expedient.expediente}"
        td= validation.expert.nombre
        td= validation.city.ciudad
        td= validation.city.estado

        td= link_to 'Show', validation
        td= link_to 'Edit', edit_validation_path(validation)
        td= link_to 'Formato', reports_validacion_path(validation.registry_id)
        td= link_to 'Destroy', validation, method: :delete, data:{ confirm: 'Are you sure?'}
br
= link_to 'New Validation', new_validation_path

app/views/validations/new.html.erb
<h1>New Validation</h1>

<%= render 'form', validation: @validation %>

<%= link_to 'Back', validations_path %>

app/views/validations/show.html.slim
p#notice= notice
p
  strong Registry:
  = @validation.registry.folio
p
  strong Nombres:
  = @validation.expert.nombre

= link_to 'Edit', edit_validation_path(@validation)
| \
= link_to 'Back', validations_path